spring:
  application:
    name: machinechat
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/machinechat?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: admin
server:
  port: 8989
  servlet:
    context-path: /machinechat
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.codervibe.secondarymachinechat.model


logging:
  file.max-size: 10MB
  level:
    root: info
    com.codervibe.secondarymachinechat: info
    com.codervibe.secondarymachinechat.Mapper: debug
  file:
    path: ./log



